version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.11

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Install modules
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Unit test
          command: yarn test:unit

  compile:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}--{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Compile test
          command: yarn compile

workflows:
  version: 2
  execute_process:
    jobs:
      - install:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - lint:
          requires:
            - install
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - test:
          requires:
            - install
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - compile:
          requires:
            - install
          filters:
            branches:
              only: /.*/
